import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'

// we can not use global css as a module to use it write it in _app.js
// import '../styles/style.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>{``}</style>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="container mx-auto sm:px-6 sm:my-6 ">
          <div className="relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl sm:rounded-3xl sm:px-16 md:pt-24 lg:flex lg:gap-x-20 lg:px-24 lg:pt-0">
            <svg
              viewBox="0 0 1024 1024"
              className="absolute left-1/2 top-1/2 -z-10 h-[64rem] w-[64rem] -translate-y-1/2 [mask-image:radial-gradient(closest-side,white,transparent)] sm:left-full sm:-ml-80 lg:left-1/2 lg:ml-0 lg:-translate-x-1/2 lg:translate-y-0"
              aria-hidden="true"
            >
              <circle cx={512} cy={512} r={512} fill="url(#759c1415-0410-454c-8f7c-9a820de03641)" fillOpacity="0.7" />
              <defs>
                <radialGradient id="759c1415-0410-454c-8f7c-9a820de03641">
                  <stop stopColor="#7775D6" />
                  <stop offset={1} stopColor="#E935C1" />
                </radialGradient>
              </defs>
            </svg>
            <div className="mx-auto max-w-md text-center lg:mx-0 lg:flex-auto lg:py-32 lg:text-left">
              <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
                Hunting Coder
                <br />
                A Blog for Coders
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-300">
                The best way to learn coding is to read blogs and practice it. We are here to help you with that. We will provide you the best blogs to learn coding.
              </p>
              <div className="mt-10 flex items-center justify-center gap-x-6 lg:justify-start">
                <Link
                  href={"/blog"}
                  className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">
                  Explore
                </Link>
                <Link href={"/blog"} className="text-sm font-semibold leading-6 text-white">
                  See More <span aria-hidden="true">→</span>
                </Link>
              </div>
            </div>
            <div className="relative mt-16 h-80 lg:mt-8">
              <img
                className="absolute left-0 top-0 w-[57rem] max-w-none rounded-md bg-white/5 ring-1 ring-white/10"
                src="/coder.jpg"
                alt="App screenshot"
                width={1824}
                height={1080}
              />
            </div>
          </div>
        </div>
      </div>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Popular Blogs</h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, quas magni! Placeat suscipit sequi consequuntur ipsam neque omnis nisi illum!</p>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center rounded-xl" src="https://img.freepik.com/free-vector/web-development-concept-with-programmer-ar_107791-17049.jpg?size=626&ext=jpg&uid=R70082888&ga=GA1.2.903730306.1655306128&semt=sph" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-pink-500 mb-1">BLOG</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">How To Learn Javascript</h1>
                  <p className="leading-relaxed">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti est rem sunt nam! Harum quaerat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center rounded-xl" src="https://img.freepik.com/free-photo/html-css-collage-concept_23-2150061955.jpg?w=740&t=st=1688468706~exp=1688469306~hmac=d10d59e4bb6535e4766278fe09fec36ae04bfb1f333b20719d1855fd8a9addce" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-pink-500 mb-1">BLOG</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">How To Learn NodeJS</h1>
                  <p className="leading-relaxed">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti est rem sunt nam! Harum quaerat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center rounded-xl" src="https://img.freepik.com/free-photo/html-css-collage-concept-with-person_23-2150062008.jpg?size=626&ext=jpg&uid=R70082888&ga=GA1.1.903730306.1655306128&semt=sph" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-pink-500 mb-1">BLOG</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">How To Learn NextJS</h1>
                  <p className="leading-relaxed">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti est rem sunt nam! Harum quaerat.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    </>
  )
}
